# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billjobs', '0002_service_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='billline',
            name='note',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Note'),
        ),
    ]
