# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 12:56
from __future__ import unicode_literals

from django.db import migrations, models
from billjobs.settings import BILLJOBS_BILL_ISSUER


class Migration(migrations.Migration):

    dependencies = [
        ('billjobs', '0004_auto_20160321_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='issuer_address',
            field=models.CharField(default=BILLJOBS_BILL_ISSUER, max_length=1024),
        ),
    ]
