# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billjobs', '0007_change_service_description_field_max_len'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='number',
            field=models.CharField(blank=True, help_text='This value is set automatically.', max_length=16, unique=True, verbose_name='Bill number'),
        ),
    ]
